### ISSUE TITLE
I translated the plugin to Catalan language

### ISSUE THREAD

**Issue by marczinger** [dokufreaks/plugin-blog#109]
Hi, I recently installed and enjoyed a lot dokuwiki and the blog plugin. So I made a catalan (language from Spain, with more than 7 million of speakers around the world) translation of it for my site. I'm new to github too, so I don't know how or who send the files to be added in the repository.

Thank you, and sorry if this is not the place where post about this.

[ca.zip](https://github.com/dokufreaks/plugin-blog/files/9184303/ca.zip)

**Comment by Klap-in** [comment]
We have also a translation tool for helping with submitting translations for DokuWiki and it plugins.
For this plugin it is at  https://translate.dokuwiki.org/plugin/blog
You might use it as well.
At a later moment I could have a look in your version above.

**Comment by marczinger** [comment]
Perfect. Thank you.
