### ISSUE TITLE
new version, old date

### ISSUE THREAD

**Issue by arlt** [dokufreaks/plugin-blog#116]
a new version of the update plugin appears with an old date in the extension manager:

```
Update: Version 2022-09-08 steht zum Download bereit.
```

**Comment by fiwswe** [comment]
Can't confirm.

For me it says: _Update: New version 2023-01-12 is available_

And after updating no version is shown in the Extension Manager (as usual).

Using the Info Plugin the correct version is shown. E.g.:
`~~INFO:syntaxplugins~~`

**Comment by fiwswe** [comment]
Judging by https://github.com/dokufreaks/plugin-blog/tags the previous version was released 2022-09-08. So you semm to have missed that version as well.

Given that you had a [similar problem with another plugin](https://github.com/dokufreaks/plugin-folded/issues/81) I'd guess that there is some problem at your end. Maybe the server couldn't reach the repository? I'd have to check the code to figure out where DW gets the information about new versions and where it downloads them from. But you could do that as well and then try curl to see if you can access that URL. A good place to start looking is in https://github.com/splitbrain/dokuwiki/blob/master/lib/plugins/extension/helper/repository.php.
