### ISSUE TITLE
plugin:blog is broken

### ISSUE THREAD

**Issue by yositake** [dokufreaks/plugin-blog#18]
Hi.

I installed plugin  blog from http://www.dokuwiki.org/plugin:blog and have found 
http://github.com/dokufreaks/plugin-blog/tarball/master  seems to be broken.
The blog part of "DokuWiki Blogsuite BundleHub" is also broken??

Could you repair it  ?

Thanks.
Harumitsu

**Comment by michitux** [comment]
Closed because of no reaction after over 3 years.
