### ISSUE TITLE
{{blog>?5}} don't display any posts

### ISSUE THREAD

**Issue by snowyurik** [dokufreaks/plugin-blog#21]
Hello.
I've installed blog, include and pagelist plugins to fresh docuwiki install with zenlike theme.

I can create a new blog entrie, and it can be accessed with id=blog:myblogentry,
but there is no list of blog entries on the blog page (

And i can't find no information how to deal with this - as it written here https://www.dokuwiki.org/tips:blogging it should work, but it does not

**Comment by qwertologe** [comment]
please close this issue - it seems to be solved
