### ISSUE TITLE
Markup not rendered

### ISSUE THREAD

**Issue by feltel** [dokufreaks/plugin-blog#5]
I´ve just upgraded Dokuwiki to the most recent version, also the plugins, i.e. blog, include etc. Now I have the issue that the wiki-markup isn´t rendered in the blog page. All texts lost their linebreks and links are shown as if the link target does not exist. If I open the blog article pages the markup is rendered as expected so I think the markup got lost maybe in the include-plugin.

Unfortunately the wiki isn´t public so I cannot provide a URL but upon request I can provide pictures to show the problem.

The wiki runs ontop of an Debian Squeeze /w Apache 2.2.15 and PHP 5.3.2-1

**Comment by qwertologe** [comment]
please close - too old.
