### ISSUE TITLE
Full name instead of Login Name

### ISSUE THREAD

**Issue by ats20de** [dokufreaks/plugin-blog#66]
Ladies & Gentlemen,

not really a bug but not nice anyway: for school projects with pupils I use a DokuWiki. For privacy purposes I configured DokuWiki to show only the login name for changes which works well on normal wiki pages. With blog entries this is different: unfortunately the full name is shown. Could I change this by myself (I fear not – otherwise: how?) or could you please make this changeable by admin-options?

Regards,
Hanjo

--  
http://ats20de/blog

**Comment by michitux** [comment]
This issue should be fixed by fixing/implementing dokufreaks/plugin-include#151 as this is where the displayed name comes from.

**Comment by ats20de** [comment]
Thanks for your help, Michael.

I understand there is a certain conflict between the way the include-plugin sets different options than the core which is to be changed later by the DokuWiki-team. Till then I should use the options of the include-plugin, which offers not to choose between user name and login name but to show the user name or not. But when I include the blog now by {{blog>Blog?7&showuser=nouser}} (before: {{blog>Blog?7}}) the names are still visible. 

![screenshot](https://cloud.githubusercontent.com/assets/10727442/5992503/b90a89dc-aa2c-11e4-9eff-4b57c63418b8.png)

Where is my fault (wrong syntax?)?

**Comment by michitux** [comment]
The syntax should be `{{blog>Blog?7&nouser}}`

**Comment by ats20de** [comment]
It works. Thank you!

**Comment by michitux** [comment]
I've also just implemented a possible fix of this behavior in the include plugin, it is available in a pull request: dokufreaks/plugin-include#154 - I would be happy if you could provide some feedback if this is the behavior you expect.
