### ISSUE TITLE
When {{blog>}} are in sidebar and in article, problem...

### ISSUE THREAD

**Issue by Zatalyz** [dokufreaks/plugin-blog#78]
I want to had in my sidebar a list with the 5 last articles. But this 5 articles don't appear in the article where I list the blog.

I make screenshot example: 

In sidebar I use this syntax: 
`{{blog>fr:blog?5&linkonly}}`
and in the list article, this: 
`{{blog>fr:blog?50&linkonly}}`

![blog](https://cloud.githubusercontent.com/assets/10725489/14485519/dcb6e186-0157-11e6-846d-61548a2d023e.jpg)

So... How can I display all list articles in the sidebar and in the content page in the same time, if I want ? 

I found a "hack" with using rss flux for the moment, but it's not so good, and I make long time to understand this strange behaviour...

**Comment by michitux** [comment]
The problem was that the plugin was checking for recursive includes of the same page a bit too aggressively. This should be fixed now - please let me know if the issue still exists.
