### ISSUE TITLE
some dates and tags are hidden

### ISSUE THREAD

**Issue by thibaud** [dokufreaks/plugin-blog#9]
Hi !
Thanks for this great plugin ! I use blog and include plugins to present the last contributions on a page. However, dates are not really effective, for example if I backup the wiki. So I use the meta plugin to fix date, with the "date created" parameter. That works, but only at once condition : posts have to be open alone first, or dates and tags don't display...
Sometimes, neither dates and tags appear.
It's not a cache problem, because I cleaned it first.
In the faq, it's writtent to remove the <dokuwiki>/data/index/cdate.idx . cdate.idx don't exist, but I delete all files in index ; but the problem persist.
A solution is probably to open all pages in a navigator, for example with this script to open all files in localhost/dokuwiki/fr:trace-libre/ namespace :

find -name "*.txt" | while read f ; do firefox $( echo "$f"  | sed -e  "s/\//:/g" -e "s/.txt//g" -e "s/.:/http:\/\/localhost\/dokuwiki\/doku.php?id=fr:trace-libre:/g") ; done

But  I have 175 pages, so it's not easy for firefox to support this...
Is there a solution to do that without the navigator ?

Best regards,
Thibaud.

**Comment by LarsGit223** [comment]
I guess this can be closed?
