### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by glensc** [dokufreaks/plugin-blog#90]
1. last github tag is from 2009-09-12 … https://github.com/dokufreaks/plugin-blog/releases
2. version in .txt file is  2016-04-26 … https://github.com/dokufreaks/plugin-blog/blob/5a8b27251ef7ea0c62a75c97f8e52fb5267a762f/plugin.info.txt

**Comment by LarsGit223** [comment]
The version is up-to-date now.
