### ISSUE TITLE
startSectionEdit errors on latest DokuWiki “Greebo”

### ISSUE THREAD

**Issue by sylvaticus** [dokufreaks/plugin-blog#92]
Just updated DokuWiki to the latest version (“Greebo”), but blog page now shows the following errors

```
startSectionEdit: $data "plugin_include_start" is NOT an array! One of your plugins needs an update.
startSectionEdit: $data "plugin_include_end" is NOT an array! One of your plugins needs an update.
startSectionEdit: $data "section" is NOT an array! One of your plugins needs an update.
startSectionEdit: $data "plugin_include_editbtn" is NOT an array! One of your plugins needs an update.
```

Also, entering new blog items is impossible as an error `Failed to handle action: preview` is issue

Thank you

EDIT: The `Failed to handle action: preview` error[ has already been fixed in master](https://github.com/dokufreaks/plugin-blog/commit/f6a7fa74d53e9808582ed0c1ec80ec9f31f4adff).

**Comment by sylvaticus** [comment]
This issue (for the Blog plugin) seems to be related to this issue (for the relevant DokuWiki documentation):

https://github.com/splitbrain/dokuwiki/issues/2290

**Comment by sylvaticus** [comment]
How to implement the re-factored section edit:

https://www.dokuwiki.org/devel:section_editor

**Comment by Klap-in** [comment]
General issue: https://github.com/splitbrain/dokuwiki/issues/2290

Please see for examples how to fix a plugin:
https://github.com/dokufreaks/plugin-include/commit/de790317615bccbc2a2276b1d8c455e2ae5a9090
https://github.com/selfthinker/dokuwiki_plugin_wrap/pull/162

**Comment by michitux** [comment]
This should already be fixed by updating the include plugin. Note that even though no new version has been released you can just update the include plugin.

**Comment by sylvaticus** [comment]
I confirm that clicking "re-install" on the include plugin solves the `startSectionEdit` issue (even if the installed version of the include plugin remained the same, 2017-08-24).

**Comment by asheenlevrai** [comment]
I have only this message:
### startSectionEdit: $data "section" is NOT an array! One of your plugins needs an update.
However I havn't installed the plugin "plugin-blog". I thought this message was caused by the plugin "editSection2". Am I wrong? How can I determine which plugin causes the message?
Tx.
-a-

**Comment by LarsGit223** [comment]
Try disabling the plugin, re-fresh the cache and page and see if you still get the message.

**Comment by LarsGit223** [comment]
There also seems to be a PR/a fix pending for editsections2 , see https://github.com/kazmiya/dokuwiki-plugin-editsections2/pull/11/files
