### ISSUE TITLE
"~~DRAFT~~" does not work

### ISSUE THREAD

**Issue by shimmtak** [dokufreaks/plugin-blog#96]
Hi, thank you for the nice tool.

It looks that the "\~\~DRAFT\~\~" syntax does not work.

I placed the syntax in a blog article, the article was immediately displayed in read mode.

The environment : “Greebo” on PHP 5.6.21. CentOS7 (4.14.33-300.1.1)
and “Frusterick Manners” on PHP 5.3.3, CentOS6(2.6.32-642.6.2)

**Comment by shimmtak** [comment]
Sorry, I recheck the function, I confirm that the syntax works.
I close this issue.

**Comment by LarsGit223** [comment]
Never mind, thanks for re-checking.
